# Configuração do GitHub Pages
title: Grazy Batista - UGC Creator
description: Site pessoal da Grazielly Batista, UGC Creator especializada em conteúdo sobre saúde preventiva, estética, autocuidado e bem-estar.
author: Grazielly Batista
url: "https://nicolasdayvison.github.io"
baseurl: "/grazy-web"

# Configurações do Jekyll
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Configurações de SEO
lang: pt-BR
locale: pt_BR

# Configurações de compressão
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

# Configurações de cache
cache_enabled: true 